#--------------------------------------------------------------------------------------------------
# See 'Readme.md' for information
#--------------------------------------------------------------------------------------------------
variables:
  NO_PROXY: "gitlab.devtools.intel.com"
  
before_script:
  - git config --global http.proxy "${HTTP_PROXY}"
  - git config --global https.proxy "${HTTPS_PROXY}"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
  - export http_proxy="${HTTP_PROXY}"
  - export https_proxy="${HTTPS_PROXY}"
  - export no_proxy="${NO_PROXY}"
  - export GITTAG=`git describe --tags --abbrev=0 2> /dev/null`

# the gta-unit-test is a container that remains alive across builds/tests.  clean up
# the gitlab url otherwise they accumulate and expire, causing pipelines to fail.
after_script:
  - git config --global --unset url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf

stages:
  - build
  - test
  - simulator

# invoke the simulator build on 'master' and 'v*/develop' branches,
# passing the current commit and branch name as variables
simulator:
  stage: simulator
  trigger: 
    project: sst/isecl/tools/gta-simulator
    branch: master
  only: 
    - master
    - /^v.*\/develop$
    - feature/development-simulator
  variables:
    GTA_COMMIT: $CI_COMMIT_SHORT_SHA
    GTA_BRANCH: $CI_COMMIT_BRANCH
    GTA_TAG: $GITTAG

build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - make all
    - make build_test
  artifacts:
    paths:
      - "out/trustagent-*.bin"
      - "out/tagent"
      - "out/*.test"
    expire_in: 1 week

test:
  stage: test
  image: gta-devel
  tags:
    - gta
  script:
    - export CGO_CFLAGS_ALLOW="-f.*"
    - go test ./... -tags=unit_test -coverpkg=./... -coverprofile out/cover.out
    - go tool cover -func out/cover.out
    - go tool cover -html=out/cover.out -o out/cover.html
  artifacts:
    paths:
      - "out/cover.html"      
